# =========================================================
# APP ENTORNO AUDIT
# =========================================================
spring.application.name=sharemechat-audit
spring.datasource.url=jdbc:mysql://db1-sharemechat-audit.c1gsc6qg4l8y.eu-central-1.rds.amazonaws.com:3306/db1_sharemechat_audit
auth.cookieDomain=.audit.sharemechat.com
jwt.secret=${JWT_SECRET_AUDIT}
consent.hmacSecret=${CONSENT_SECRET_AUDIT}
app.frontend.reset-url=https://audit.sharemechat.com/reset-password
app.frontend.verify-email-product-url=https://audit.sharemechat.com/verify-email
app.frontend.verify-email-admin-url=https://admin.audit.sharemechat.com/verify-email
kyc.veriff.callback-url=https://audit.sharemechat.com/api/kyc/veriff/webhook